"use client";

import { useMemo, useRef, useState } from "react";

type Source = "cash" | "campaign_payout" | "affiliate" | "pr_gift";
type Income = { id: string; source: Source; brand: string; description: string; date: string; amount: number; status: "recorded" | "pending" };
type Expense = { id: string; name: string; category: string; amount: number; confidence: number; percentage: number; confirmed: boolean };

const initialIncome: Income[] = [
  { id: "i1", source: "campaign_payout", brand: "Glow Recipe", description: "TikTok skincare campaign", date: "2026-06-18", amount: 1800, status: "recorded" },
  { id: "i2", source: "cash", brand: "Nori Studio", description: "UGC video collaboration", date: "2026-05-29", amount: 950, status: "recorded" },
  { id: "i3", source: "pr_gift", brand: "Aesop", description: "Lucent Facial Concentrate", date: "2026-05-12", amount: 145, status: "recorded" },
  { id: "i4", source: "affiliate", brand: "Shopee", description: "May creator commission", date: "2026-05-31", amount: 324.6, status: "recorded" },
  { id: "i5", source: "campaign_payout", brand: "Laneige", description: "Reels product launch", date: "2026-04-08", amount: 1240, status: "recorded" },
  { id: "i6", source: "cash", brand: "Sunday Folks", description: "Photo content package", date: "2026-03-22", amount: 680, status: "recorded" },
  { id: "i7", source: "affiliate", brand: "Lazada", description: "March affiliate commission", date: "2026-03-31", amount: 218.4, status: "recorded" },
  { id: "i8", source: "campaign_payout", brand: "Love, Bonito", description: "Lunar New Year campaign", date: "2026-02-14", amount: 2200, status: "recorded" },
];
const initialExpenses: Expense[] = [
  { id: "e1", name: "Adobe Creative Cloud", category: "Editing software", amount: 79.9, confidence: 96, percentage: 100, confirmed: true },
  { id: "e2", name: "Wireless lavalier microphone", category: "Filming equipment", amount: 168, confidence: 94, percentage: 100, confirmed: true },
  { id: "e3", name: "Mobile phone plan", category: "Shared use", amount: 58, confidence: 62, percentage: 40, confirmed: false },
];

const labels = {
  en: { title: "Know your creator income. File with confidence.", lede: "Track campaign payments, cash income, affiliate commissions and PR gifts in one clear annual view.", total: "Total income", taxable: "Taxable income", reserve: "Suggested tax reserve", income: "Income records", expenses: "Deductible expenses", addIncome: "+ Add income", addExpense: "+ Add expense", all: "All", export: "Download annual CSV", gift: "PR gift valuation", giftText: "Record a gift at its fair market retail value. Confirm the amount before it is included in your tax calculation.", confirmed: "Confirmed", pending: "Needs confirmation", disclaimer: "Estimates and suggestions only — this tool is not tax advice. Confirm your records and refer to the latest IRAS guidance before filing.", deadline: "Next e-filing deadline", details: "Details", save: "Save record", cancel: "Cancel", name: "Brand / payer", desc: "Description", amount: "Amount (SGD)", source: "Source", expenseName: "Expense name", category: "Category", workUse: "Work-use %", noRecords: "No records yet." },
  zh: { title: "把创作者收入理清，报税更安心。", lede: "将 campaign 打款、现金收入、affiliate 分成和 PR 赠品汇总到一份年度视图。", total: "总收入", taxable: "应税收入", reserve: "建议预留报税金", income: "收入记录", expenses: "可抵扣支出", addIncome: "+ 添加收入", addExpense: "+ 添加支出", all: "全部", export: "下载年度 CSV", gift: "PR 赠品价值估算", giftText: "按公开市场零售价记录赠品。在计入应税收入前，请确认金额。", confirmed: "已确认", pending: "待确认", disclaimer: "本工具只提供预估与建议，并非税务意见。报税前请确认记录，并以最新 IRAS 指引为准。", deadline: "下一次电子报税截止日", details: "明细", save: "保存记录", cancel: "取消", name: "品牌 / 付款方", desc: "描述", amount: "金额（SGD）", source: "收入来源", expenseName: "支出名称", category: "类别", workUse: "工作用途 %", noRecords: "暂无记录。" },
};
const format = (n: number) => new Intl.NumberFormat("en-SG", { style: "currency", currency: "SGD" }).format(n);
const sourceNames: Record<Source, string> = { cash: "Cash", campaign_payout: "Campaign", affiliate: "Affiliate", pr_gift: "PR gift" };

export default function Home() {
  const [lang, setLang] = useState<"en" | "zh">("en"); const [incomes, setIncomes] = useState(initialIncome); const [expenses, setExpenses] = useState(initialExpenses);
  const [filter, setFilter] = useState<"all" | Source>("all"); const [period, setPeriod] = useState<"day" | "week" | "month" | "quarter">("month"); const [modal, setModal] = useState<"income" | "expense" | null>(null); const formRef = useRef<HTMLFormElement>(null); const t = labels[lang];
  const total = useMemo(() => incomes.filter(x => x.status === "recorded").reduce((a, x) => a + x.amount, 0), [incomes]);
  const deductible = useMemo(() => expenses.filter(x => x.confirmed).reduce((a, x) => a + x.amount * x.percentage / 100, 0), [expenses]); const taxable = Math.max(0, total - deductible); const reserve = taxable * (taxable > 20000 ? .06 : .03);
  const addRecord = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const d = new FormData(event.currentTarget); if (modal === "income") setIncomes(x => [{ id: crypto.randomUUID(), source: d.get("source") as Source, brand: String(d.get("brand")), description: String(d.get("description")), date: String(d.get("date")), amount: Number(d.get("amount")), status: "recorded" }, ...x]); else setExpenses(x => [{ id: crypto.randomUUID(), name: String(d.get("name")), category: String(d.get("category")), amount: Number(d.get("amount")), confidence: 70, percentage: Number(d.get("percentage")), confirmed: true }, ...x]); setModal(null); };
  const downloadCsv = () => { const rows = ["Type,Source/Category,Name/Brand,Description,Amount SGD,Status", ...incomes.map(x => `Income,${sourceNames[x.source]},${x.brand},${x.description},${x.amount.toFixed(2)},${x.status}`), ...expenses.map(x => `Expense,${x.category},${x.name},,${(x.amount*x.percentage/100).toFixed(2)},${x.confirmed ? "confirmed" : "unconfirmed"}`)]; const blob = new Blob([rows.join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "Influencees_2026_tax_summary.csv"; a.click(); URL.revokeObjectURL(url); };
  const shown = filter === "all" ? incomes : incomes.filter(x => x.source === filter);
  const analysis = useMemo(() => groupIncome(incomes, period), [incomes, period]); const peak = analysis.reduce((a, x) => x.amount > a.amount ? x : a, analysis[0] ?? { label: "—", amount: 0, count: 0 }); const max = Math.max(...analysis.map(x => x.amount), 1);
  return <main className="shell"><header><div className="brand"><span>✦</span><div><strong>Influencees</strong><small>CREATOR FINANCE</small></div></div><div className="header-actions"><div className="deadline"><i />{t.deadline}: <b>18 Apr 2027</b></div><div className="language"><button className={lang === "en" ? "active" : ""} onClick={() => setLang("en")}>EN</button><button className={lang === "zh" ? "active" : ""} onClick={() => setLang("zh")}>中文</button></div></div></header>
    <section className="hero"><p className="eyebrow">CREATOR BUSINESS TOOLS · 2026</p><h1>{t.title}</h1><p>{t.lede}</p></section>
    <section className="stats"><Stat label={t.total} value={format(total)} tone="violet" foot={`${incomes.length} ${t.details.toLowerCase()}`} /><Stat label={t.taxable} value={format(taxable)} tone="gold" foot={`${format(deductible)} ${lang === "en" ? "approved deductions" : "已确认抵扣"}`} /><Stat label={t.reserve} value={format(reserve)} tone="green" foot={lang === "en" ? "Planning estimate" : "规划预估"} /></section>
    <section className="panel analysis"><div className="section-head"><div><p className="eyebrow">01 / INCOME VIEW</p><h2>{lang === "en" ? "Income analysis" : "收入分析"}</h2></div><div className="tabs period-tabs">{(["day", "week", "month", "quarter"] as const).map(x => <button key={x} className={period === x ? "selected" : ""} onClick={() => setPeriod(x)}>{({ day: "按天", week: "按周", month: "按月", quarter: "按季度" }[x])}</button>)}</div></div><div className="analysis-stats"><Mini label={lang === "en" ? "Period income" : "期间收入"} value={format(analysis.reduce((a, x) => a + x.amount, 0))} /><Mini label={lang === "en" ? "Average per period" : "每期平均"} value={format(analysis.length ? analysis.reduce((a, x) => a + x.amount, 0) / analysis.length : 0)} /><Mini label={lang === "en" ? "Best period" : "最高期间"} value={peak.label} /></div><div className="chart">{analysis.map(x => <div className="bar-wrap" key={x.label}><div className="bar-value">{format(x.amount)}</div><div className="bar" style={{ height: `${Math.max(6, x.amount / max * 100)}%` }} /><span>{x.label}</span><small>{x.count} {lang === "en" ? "records" : "笔"}</small></div>)}</div></section>
    <section className="panel"><div className="section-head"><div><p className="eyebrow">02 / {lang === "en" ? "TRACK" : "记录"}</p><h2>{t.income}</h2></div><button className="primary" onClick={() => setModal("income")}>{t.addIncome}</button></div><div className="tabs">{(["all", "cash", "campaign_payout", "affiliate", "pr_gift"] as const).map(x => <button key={x} className={filter === x ? "selected" : ""} onClick={() => setFilter(x)}>{x === "all" ? t.all : sourceNames[x]}</button>)}</div><div className="records">{shown.map(x => <div className="record" key={x.id}><div className="source-icon">{x.source === "pr_gift" ? "🎁" : x.source === "affiliate" ? "↗" : "●"}</div><div className="record-copy"><strong>{x.brand}</strong><span>{x.description} · {x.date}</span></div><em className={x.status === "recorded" ? "ok" : "pending"}>{x.status === "recorded" ? t.confirmed : t.pending}</em><b>{format(x.amount)}</b></div>)}{!shown.length && <p className="empty">{t.noRecords}</p>}</div></section>
    <div className="two-col"><section className="receipt"><p className="eyebrow">02 / PR GIFT</p><h2>{t.gift}</h2><p>{t.giftText}</p><div className="receipt-line"><span>Aesop · Lucent Facial Concentrate</span><b>{format(145)}</b></div><div className="receipt-meta"><span>Official retail price match</span><span>Confidence: 92%</span></div><button className="text-button" onClick={() => setModal("income")}>{lang === "en" ? "Add a PR gift →" : "添加 PR 赠品 →"}</button></section>
    <section className="panel expenses"><div className="section-head"><div><p className="eyebrow">03 / REVIEW</p><h2>{t.expenses}</h2></div><button className="primary" onClick={() => setModal("expense")}>{t.addExpense}</button></div>{expenses.map(x => <label className="expense" key={x.id}><input type="checkbox" checked={x.confirmed} onChange={() => setExpenses(all => all.map(e => e.id === x.id ? { ...e, confirmed: !e.confirmed } : e))}/><span><strong>{x.name}</strong><small>{x.category} · {x.confidence}% confidence · {x.percentage}% work use</small></span><b>{format(x.amount * x.percentage / 100)}</b></label>)}</section></div>
    <section className="export"><div><p className="eyebrow">ANNUAL SUMMARY</p><h2>{lang === "en" ? "Ready when tax season arrives." : "报税季来临时，随时准备好。"}</h2><p>{t.disclaimer}</p></div><button className="primary export-btn" onClick={downloadCsv}>↓ {t.export}</button></section><footer>{t.disclaimer}</footer>
    {modal && <div className="overlay"><form className="modal" ref={formRef} onSubmit={addRecord}><button className="close" type="button" onClick={() => setModal(null)}>×</button><p className="eyebrow">NEW RECORD</p><h2>{modal === "income" ? t.addIncome : t.addExpense}</h2>{modal === "income" ? <><label>{t.source}<select name="source"><option value="cash">Cash</option><option value="campaign_payout">Campaign payout</option><option value="affiliate">Affiliate</option><option value="pr_gift">PR gift</option></select></label><label>{t.name}<input required name="brand" /></label><label>{t.desc}<input required name="description" /></label><label>{t.amount}<input required min="0" step="0.01" type="number" name="amount" /></label><label>Date<input required type="date" name="date" defaultValue="2026-07-24" /></label></> : <><label>{t.expenseName}<input required name="name" /></label><label>{t.category}<input required name="category" /></label><label>{t.amount}<input required min="0" step="0.01" type="number" name="amount" /></label><label>{t.workUse}<input required min="0" max="100" type="number" name="percentage" defaultValue="100" /></label></>}<button className="primary submit" type="submit">{t.save}</button></form></div>}</main>;
}
function Stat({ label, value, tone, foot }: { label: string; value: string; tone: string; foot: string }) { return <article className={`stat ${tone}`}><span>{label}</span><strong>{value}</strong><small>{foot}</small></article>; }
function Mini({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function groupIncome(incomes: Income[], period: "day" | "week" | "month" | "quarter") { const groups = new Map<string, { label: string; amount: number; count: number }>(); for (const item of incomes.filter(x => x.status === "recorded")) { const d = new Date(`${item.date}T00:00:00`); let key = item.date; let label = item.date.slice(5); if (period === "week") { const start = new Date(d); start.setDate(d.getDate() - ((d.getDay() + 6) % 7)); key = start.toISOString().slice(0, 10); label = `Wk ${key.slice(5)}`; } if (period === "month") { key = item.date.slice(0, 7); label = d.toLocaleString("en", { month: "short" }); } if (period === "quarter") { const q = Math.floor(d.getMonth() / 3) + 1; key = `${d.getFullYear()}-Q${q}`; label = `Q${q}`; } const current = groups.get(key) ?? { label, amount: 0, count: 0 }; current.amount += item.amount; current.count += 1; groups.set(key, current); } return [...groups.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([, v]) => v); }
